image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - golang.go
    - neonxp.gotools
    - ethan-reesor.vscode-go-test-adapter
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
