tasks:
  - name: Install Go modules and mob.sh
    init: |
      curl -sL install.mob.sh | sudo sh

vscode:
  extensions:
    - golang.go
    - neonxp.gotools
    - ethan-reesor.vscode-go-test-adapter
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
