
tasks:
 - name: Setup
   init: |
    curl -sL install.mob.sh | sudo sh
vscode:
  extensions:
    - ethan-reesor.vscode-go-test-adapter
    - hbenl.vscode-test-explorer
    - golang.go
    - neonxp.gotools
